apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    image.rgistry: "https://hub.docker.com/"
    github-url: "https://github.com/daws-78s/k8-resources/blob/main/04-labels.yaml"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
  