kind: Pod
apiVersion: v1
metadata: pod-configmap
spec:
  containers:
    - name: nginx
      image: nginx
      env:
       - name: course
         valueFrom:
          configMapKeyRef:
           name: sai
           key: course
       - name: desig
          valueFrom:
           configMapKeyRef:
            name: sai
            key: Designation
           