kind: Pod
apiVersion: v1
metadata: pod-configmap
spec:
  containers:
    - name: nginx
      image: nginx
      env:
       - name: course
         valueFrom:
          confrigMapRef:
           name: sai
           value: course
        - name: desig
          valueFrom:
          configMapRef:
           name: sai
           value: Designation
           